/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false --strict-vars=false --env-interface=CloudflareBindings src/cloudflare-bindings.d.ts` (hash: c33ffd0bb79fb1e5eb3f3c52bdd3895d)
interface __BaseEnv_CloudflareBindings {
	ATTACHMENTS: R2Bucket;
	DB: D1Database;
	EMAIL: SendEmail;
	ASSETS: Fetcher;
	EMAIL_PROVIDER: string;
	CLOUDFLARE_MAIL_DOMAINS: string;
	APP_URL: string;
	DISABLE_PUBLIC_SETUP: string;
	DISABLE_EXTERNAL_AUTH: string;
	CHAT_ENABLED: string;
	REALTIME_ACCOUNT_ID: string;
	REALTIME_APP_ID: string;
	REALTIME_PARTICIPANT_PRESET: string;
	CHAT_HUB: DurableObjectNamespace<import('./worker').ChatHub>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import('./worker');
		durableNamespaces: 'ChatHub';
	}
	interface Env extends __BaseEnv_CloudflareBindings {}
}
interface CloudflareBindings extends __BaseEnv_CloudflareBindings {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string
		? EnvType[Binding]
		: string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<
		Pick<
			Cloudflare.Env,
			| 'EMAIL_PROVIDER'
			| 'CLOUDFLARE_MAIL_DOMAINS'
			| 'APP_URL'
			| 'DISABLE_PUBLIC_SETUP'
			| 'DISABLE_EXTERNAL_AUTH'
			| 'CHAT_ENABLED'
			| 'REALTIME_ACCOUNT_ID'
			| 'REALTIME_APP_ID'
			| 'REALTIME_PARTICIPANT_PRESET'
		>
	> {}
}
